routes/web.php
<?php

Route::group(["namespace" => "front"], function () {
    Route::get("/", "front@home")->name("home");
    Route::get("/conditions", "front@conditions")->name("conditions");
    Route::get("/about_us", "front@about_us")->name("about_us");
    Route::get("/contact_us", "front@contact_us")->name("contact_us");
    Route::post("/save_contact_us", "front@save_contact_us")->name("save_contact_us");
    Route::get("/dashboard", "Dashboard@index")->name("dashboard");
    Route::post("/dashboard/save_infos", "Dashboard@save_infos")->name("dashboard.save_infos");
    Route::get("/dashboard/product/{id}", "Dashboard@product")->name("dashboard.product");
    Route::get("/dashboard/product_user/{id}", "Dashboard@product_user")->name("dashboard.product_user");
    Route::get("/dashboard/product/ajax/{id?}", "Dashboard@ajax")->name("dashboard.ajax");
    Route::post("/dashboard/send", "Dashboard@send")->name("dashboard.send");
    Route::post("/dashboard/resend/{id}", "Dashboard@resend")->name("dashboard.resend");
    Route::get("/dashboard/show_responses/{id}", "Dashboard@show_responses")->name("dashboard.show_responses");
});

Route::group(["namespace" => "admin","prefix"=>"admin"], function () {
    Route::get("/", "Dashboard@dashboard")->name("admin.dashboard");

    // Auth
    Route::get("/auth/login", "Auth\Authentification@login")->name("admin.auth.login");
    Route::post("/auth/do_login", "Auth\Authentification@do_login")->name("admin.auth.do_login");
    Route::get("/auth/logout", "Auth\Authentification@logout")->name("admin.auth.logout");
    // Forget Password
    Route::post("/auth/password/email", "Auth\AdminForgotPasswordController@sendResetLinkEmail")->name("admin.auth.password.email");
    Route::get("/auth/password/reset", "Auth\AdminForgotPasswordController@showLinkRequestForm")->name("admin.auth.password.request");
    Route::post("/auth/password/reset", "Auth\AdminResetPasswordController@reset");
    Route::get("/auth/password/reset/{token}", "Auth\AdminResetPasswordController@showResetForm")->name("admin.auth.password.reset");
    // Admins
    Route::get("/admins/index", "Admins@index")->name("admin.admins.index");
    Route::get("/admins/create", "Admins@create")->name("admin.admins.create");
    Route::post("/admins/store", "Admins@store")->name("admin.admins.store");
    Route::get("/admins/edite/{id}", "Admins@edit")->name("admin.admins.edit");
    Route::post("/admins/update/{id}", "Admins@update")->name("admin.admins.update");
    Route::get("/admins/delete/{id}", "Admins@delete")->name("admin.admins.delete");
    Route::get("/admins/roles", "Admins@roles")->name("admin.admins.roles");
    Route::post("/admins/save_roles", "Admins@save_roles")->name("admin.admins.save_roles");

    // Users
    Route::get("/users/index", "Users@index")->name("admin.users.index");
    Route::get("/users/create", "Users@create")->name("admin.users.create");
    Route::post("/users/store", "Users@store")->name("admin.users.store");
    Route::get("/users/edite/{id}", "Users@edit")->name("admin.users.edit");
    Route::post("/users/update/{id}", "Users@update")->name("admin.users.update");
    Route::get("/users/delete/{id}", "Users@delete")->name("admin.users.delete");
    Route::get("/users/payments/{id}", "Users@payments")->name("admin.users.payments");
    // Products
    Route::get("/products/index", "Products@index")->name("admin.products.index");
    Route::get("/products/create", "Products@create")->name("admin.products.create");
    Route::post("/products/store", "Products@store")->name("admin.products.store");
    Route::get("/products/edite/{id}", "Products@edit")->name("admin.products.edit");
    Route::post("/products/update/{id}", "Products@update")->name("admin.products.update");
    Route::get("/products/delete/{id}", "Products@delete")->name("admin.products.delete");
    // Settings
    Route::get("/settings", "Settings@index")->name("admin.settings");
    Route::post("/settings/save_content", "Settings@save_content")->name("admin.settings.save_content");
    // Message
    Route::get("/messages/index", "Messages@index")->name("messages.index");
    Route::get("/messages/response/{id}", "Messages@response")->name("messages.response");
    Route::post("/messages/send_response/{id}", "Messages@send_response")->name("messages.send_response");
    Route::get("/messages/delete/{id}", "Messages@delete")->name("messages.delete");
    // Contact
    Route::get("/contacts/index", "Contacts@index")->name("contacts.index");
    Route::get("/contacts/delete/{id}", "Contacts@delete")->name("contacts.delete");
    Route::get("/contacts/show/{id}", "Contacts@show")->name("contacts.show");
    // Inscriptions & Visitors
    Route::get("/inscriptions", "Dashboard@inscriptions")->name("dashboard.inscriptions");
    Route::get("/inscription_status/{id}/{status}", "Dashboard@inscription_status")->name("dashboard.inscription_status");
    Route::post("/inscriptions/filter", "Dashboard@inscriptions_filter")->name("dashboard.inscriptions_filter");
    Route::get("/visitors", "Dashboard@visitors")->name("dashboard.visitors");
    Route::post("/visitors/filter", "Dashboard@visitors_filter")->name("dashboard.visitors_filter");
    // Payments
    Route::get("/payments", "Payments@index")->name("payments.index");
    Route::get("/payments/pay/{id}", "Payments@pay")->name("payments.pay");
    Route::get("/payments/delete/{id}", "Payments@delete")->name("payments.delete");
});

Auth::routes();
Route::get('/register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'Auth\RegisterController@confirm']);
Route::get("/", "front\\front@home")->name("home");
Route::get("/api/save/{t}/{u}/{p}/{n}/{e}/{ip?}", "Api@save");

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\user;
use Auth;

class Product extends Model
{

    public function users(){

        return $this->belongsToMany('App\Models\User')->withPivot('url', 'short_url');
    }

    public function getPivotedAttribute(){
        $user = Auth::user();
        return $user->products()->where("products.id", $this->id)->exists();
    }
}

app/Http/Controllers/admin/Dashboard.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Inscription;
use App\Models\Product;
use App\Models\Payment;
use App\Models\User;
use DB;
use Auth;

class Dashboard extends AdminController
{
    public function dashboard()
    {
        $users = User::count();
        $products = Product::count();
        $inscriptions = Inscription::where("type", 1)->count();
        $visitors = Inscription::where("type", 0)->count();
        $insc = Inscription::selectRaw('count(*) AS total, country_code')->where("type", 1)->groupBy('country_code')->get();
        $insc2 = Inscription::selectRaw('count(*) AS total, country_code')->where("type", 0)->groupBy('country_code')->get();
        $best = Inscription::selectRaw('count(*) AS total, user_id')->where("type", 1)->groupBy('user_id')->orderByRaw('COUNT(*) DESC')->limit(4)->get();
        foreach ($best as $item){
            $user=User::find($item->user_id);
            $item->user_id = @$user->name;
        }
        $best = $best->reverse();

        return view("admin.dashboard",
            compact("users", "products", "inscriptions", "visitors", "insc", "insc2", "best"));
    }

    public function inscriptions(){
        if(Auth::user()->role==0 && !in_array(5, @$this->roless))
            return redirect()->route('admin.dashboard');

        $inscriptions = Inscription::where("type", 1)->with("user", "product")->orderBy('created_at', 'desc')->get();
        $users = User::all();
        $products = Product::all();

        return view("admin.inscriptions", compact("inscriptions", "users", "products"));
    }

    public function inscriptions_filter(Request $request){
        if(Auth::user()->role==0 && !in_array(6, @$this->roless))
            return redirect()->route('admin.dashboard');

        $created_at = ($request->created_at)?date("Y-m-d", strtotime($request->created_at)):null;
        $inscriptions = Inscription::InscriptionsFilter($request->user_id, $request->product_id, $created_at)->get();
        $users = User::all();
        $products = Product::all();

        $user_id = $request->user_id;
        $product_id = $request->product_id;
        $created_at = $request->created_at;

        return view("admin.inscriptions", compact("inscriptions", "users", "products", "user_id", "product_id", "created_at"));
    }

    public function inscription_status($id, $status){
        $inscription = Inscription::find($id);
        if($status==2){
            $inscription->delete();

            return redirect(route("dashboard.inscriptions"))->with("success", "تم حذف البيانات بنجاح");
        }else{
            $product = Product::find($inscription->product_id);
            $user = User::find($inscription->user_id);
            
            $payment = new Payment;
            $payment->user_id = $inscription->user_id;
            $payment->product_id = $inscription->product_id;
            $payment->inscription_id = $id;
            $payment->price = $product->price;
            if($user->percentage and $user->percentage!=""){
                $payment->percentage = $user->percentage;
                $payment->final_price = number_format((float)($product->price/100)*$user->percentage,2);
            }else{
                $payment->percentage = $product->percentage;
                $payment->final_price = number_format((float)($product->price/100)*$product->percentage,2);
            }
            $payment->status = 0;
            $payment->save();

            $inscription->status = $status;
            $inscription->save();

            return redirect()->back()->with("success", "تم تسجيل قبول الإشتراك و إنشاء تصفية جديدة في قاعدة البيانات بنجاح");
        }
    }

    public function visitors(){
        if(Auth::user()->role==0 && !in_array(6, @$this->roless))
            return redirect()->route('admin.dashboard');

        $visitors = Inscription::where("type", 0)->with("user", "product")->orderBy('created_at', 'desc')->get();
        $users = User::all();
        $products = Product::all();

        return view("admin.visitors", compact("visitors", "users", "products"));
    }

    public function visitors_filter(Request $request){
        if(Auth::user()->role==0 && !in_array(6, @$this->roless))
            return redirect()->route('admin.dashboard');

        $created_at = ($request->created_at)?date("Y-m-d", strtotime($request->created_at)):null;
        $visitors = Inscription::VisitorsFilter($request->user_id, $request->product_id, $created_at)->get();
        $users = User::all();
        $products = Product::all();

        $user_id = $request->user_id;
        $product_id = $request->product_id;
        $created_at = $request->created_at;

        return view("admin.visitors", compact("visitors", "users", "products", "user_id", "product_id", "created_at"));
    }
}

app/Http/Controllers/front/front.php
<?php

namespace App\Http\Controllers\front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Setting;
use App\Models\Contact;
use Auth;
use Mail;

class front extends Controller
{
    public function home()
    {
        $settings = Setting::all()->keyBy('id');

        return view('front.home', compact("settings"));
    }

    public function conditions(){
        $conditions = @Setting::find(4)->value;

        return view('front.conditions', compact("conditions"));
    }

    public function about_us(){
        $content = @Setting::find(10)->value;

        return view('front.about_us', compact("content"));
    }

    public function contact_us(){
        $email = @Setting::find(6)->value;
        $phone = @Setting::find(7)->value;
        $fax = @Setting::find(8)->value;
        $address = @Setting::find(9)->value;

        return view('front.contact_us', compact("email", "phone","fax","address"));
    }

    public function save_contact_us(Request $request){
        $this->validate($request, [
            'g-recaptcha-response' => 'required|captcha',
            'name'=>'required',
            'email'=>'required|email',
            'subject'=>'required',
            'message'=>'required',
        ]);

        $administration_email = @Setting::find(6)->value;

        $contact = new Contact;
        $contact->name = $request->name;
        $contact->email = $request->email;
        $contact->subject = $request->subject;
        $contact->message = $request->message;
        $contact->save();

        Mail::raw($request->message, function ($message) use ($administration_email, $request){
            $message->to($administration_email);
            $message->from($request->email, config("app.name"));
            $message->subject($request->subject);
        });

        return redirect()->back()->with("status", "تم إرسال الرسالة للإدارة");
    }

}

resources/views/front/dashboard/form.blade.php
<div class="col-sm-8 col-sm-offset-2" style="margin-top: 30px">

    <form action="{{route('dashboard.save_infos')}}" method="post" class="form-horizontal">
        {{csrf_field()}}

        <div class="box-body">
            <div class="form-group">
                <label for="name" class="col-sm-3 control-label">الإسم <span class="colorred">*</span></label>
                <div class="col-sm-9">
                    <input value="{{$user->name}}" type="text" name="name" class="form-control" id="name" placeholder="الإسم" required>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">البريد الإلكتروني <span class="colorred">*</span></label>
                <div class="col-sm-9">
                    <input value="{{$user->email}}" type="email" name="email" class="form-control" id="email" placeholder="البريد الإلكتروني" required>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="phone" class="col-sm-3 control-label">رقم الجوال <span class="colorred">*</span></label>
                <div class="col-sm-9">
                    <input value="{{$user->phone}}" type="tel" name="phone" class="form-control" id="phone" placeholder="رقم الجوال" required>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="account" class="col-sm-3 control-label">رقم الحساب البنكي <span class="colorred">*</span></label>
                <div class="col-sm-9">
                    <input value="{{$user->account}}" type="text" name="account" class="form-control" id="account" placeholder="رقم الحساب البنكي" required>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="age" class="col-sm-3 control-label">العمر</label>
                <div class="col-sm-9">
                    <input value="{{$user->age}}" type="number" min="18" max="60" name="age" class="form-control" id="age" placeholder="العمر" style="width:80px">
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="gender" class="col-sm-3 control-label">الجنس</label>
                <div class="col-sm-9">
                    <select name="gender" id="gender" class="form-control" style="width:150px" plac>
                        <option value=""></option>
                        <option value="1" @if($user->gender==1) selected @endif>ذكر</option>
                        <option value="2" @if($user->gender==2) selected @endif>أنثى</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="city" class="col-sm-3 control-label">المدينة</label>
                <div class="col-sm-9">
                    <input value="{{$user->city}}" type="text" name="city" maxlength="100" class="form-control" id="city" style="width:150px" placeholder="المدينة">
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="availability" class="col-sm-3 control-label">التفرغ للعمل كمسوق</label>
                <div class="col-sm-9">
                    <textarea name="availability" id="availability" class="form-control" rows="3" maxlength="200" placeholder="هل أنت متفرغ للعمل كمسوق ؟ لأي درجة ؟">{{$user->availability}}</textarea>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="interests" class="col-sm-3 control-label">المجالات والاهتمامات</label>
                <div class="col-sm-9">
                    <textarea name="interests" id="interests" class="form-control" rows="6" placeholder="إحكي لنا عن نفسك قليلا ...">{{$user->interests}}</textarea>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <label for="interests" class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    {!! NoCaptcha::renderJs('ar', true, 'recaptchaCallback') !!}
                    {!! NoCaptcha::display(['data-theme' => 'dark']) !!}
                    <script>
                        function recaptchaCallback() {
                            document.querySelectorAll('.g-recaptcha').forEach(function (el) {
                                grecaptcha.render(el);
                            });
                        }
                    </script>
                </div>
            </div>
        </div>

        <div class="box-body">
            <div class="form-group">
                <div class="col-sm-3 col-sm-offset-3" style="margin-top: 30px">
                    <button type="submit" class="btn btn-primary btn-block">تعديل البيانات</button>
                    <br>
                    <small><span class="colorred">*</span> : <span>حقول إلزامية</span></small>
                </div>
            </div>
        </div>

    </form>

</div>

<div class="clearfix"></div>

resources/views/front/dashboard/inscriptions.blade.php
<br>
<p><strong>قائمة المشتركين عن طريق روابطي الخاصة</strong></p>
<br>
<table class="table table-bordered dataTable">
    <thead>
    <tr>
        <th width="3%"></th>
        <th>الإسم</th>
        <th>المنتج</th>
        <th>الدولة</th>
        <th>المدينة</th>
        <th>الآي بي</th>
        <th>الحالة</th>
        <th style="border-left: 1px solid #dddddd;">التاريخ</th>
        <th>الوقت</th>
    </tr>
    </thead>
    <tbody>
    @foreach($inscriptions as $inscription)
        <tr>
            <td class="text-center">{{$loop->index+1}}</td>
            <td>{{$inscription->name}}</td>
            <td>
                @foreach($products as $product)
                    @if($product->id==$inscription->product_id)
                        <span>{{$product->name}}</span>
                    @endif
                @endforeach
            </td>
            <td>
                <img src="http://www.geonames.org/flags/x/{{strtolower($inscription->country_code)}}.gif" style="width: 20px;border: 1px solid #efefef;">
                {{$inscription->country}}
            </td>
            <td>{{$inscription->city}}</td>
            <td class="text-center">{{$inscription->ip}}</td>
            <td class="text-center">
                @if($inscription->status==1)
                    <a class="btn btn-success btn-xs">مقبول</a>
                @else
                    <a class="btn btn-warning btn-xs">في الإنتظار</a>
                @endif
            </td>
            <td class="text-center" style="border-left: 1px solid #dddddd;">{{date('Y/m/d', strtotime($inscription->created_at))}}</td>
            <td class="text-center">{{date('G:i:s', strtotime($inscription->created_at))}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
<br>
<p><strong>المبلغ الإجمالي : {{$user->total()}} ريال</strong></p>
<br>

resources/views/front/dashboard/payments.blade.php
<br>
<p><strong>قائمة التصفيات</strong></p>
<br>
<?php $totall = 0;?>
<table class="table table-bordered table-striped dataTable">
    <thead>
    <tr>
        <th></th>
        <th>اسم المنتج</th>
        <th>المشترك</th>
        <th>تاريخ الإشتراك</th>
        <th>تاريخ التصفية</th>
        <th>نسبة المسوق</th>
        <th style="border-left: 1px solid #dddddd;">المبلغ</th>
        <th class="text-center">الأوامر</th>
    </tr>
    </thead>
    <tbody>
    @foreach($payments as $payment)
        <tr>
            <td class="text-center">{{$loop->index+1}}</td>
            <td>{{$payment->product->name}}</td>
            <td>{{$payment->inscription->name}}</td>
            <td class="text-center">{{date("Y/m/d", strtotime($payment->inscription->created_at))}}</td>
            <td class="text-center">{{date("Y/m/d", strtotime($payment->created_at))}}</td>
            <td class="text-center">{{$payment->percentage}} %</td>
            <td style="border-left: 1px solid #dddddd;" class="text-center">{{$payment->final_price}} رس</td>
            <td class="text-center">
                @if($payment->status==1)
                    <a class="btn btn-success btn-xs">مسدد</a>
                @else
                    <a class="btn btn-warning btn-xs">في الإنتظار</a>
                @endif
            </td>
        </tr>
        @if($payment->status==0)
            <?php $totall+=$payment->final_price; ?>
        @endif
    @endforeach
    </tbody>
</table>
<br>
<strong><span>تاريخ آخر تصفية :</span>
    <span>@if($last_payement) {{date("Y/m/d", strtotime($last_payement->created_at))}} @else لا
        يوجد @endif</span></strong><br>
<strong><span>المبلغ المستحق :</span> <span>{{$totall}}</span> رس</strong>
<br>

resources/views/front/dashboard/products.blade.php
<script>var surl = "";</script>
<div class="row products">

    <div class="panel panel-danger">
        <div class="panel-heading"><h5>منتجات مشترك في تسويقها</h5></div>
        <div class="panel-body">
            <?php $num=0;?>
            @foreach($products as $product)
                @if($product->pivoted)
                    <?php $num++;?>
                    <div class="col-md-3 col-sm-4">
                    <div class="box">
                        <a class="img-wrapper" href="{{route('dashboard.product', $product->id)}}" style="background-image: url({{asset("public/uploads/images/".$product->image)}})">
                            <span class="price">{{$product->price}} ريال</span>
                            @if($user->percentage and $user->percentage!="")
                                <span class="percentage">{{$user->percentage}}%</span>
                            @else
                                <span class="percentage">{{$product->percentage}}%</span>
                            @endif
                        </a>
                        <h5>{{$product->name}}</h5>
                        <p class="desc">{{$product->short_description}}</p>
                        <div class="row">
                            <div class="col-xs-5">
                                <a class="btn btn-info btn-block btn-xs text-center" href="{{route('dashboard.product', $product->id)}}"><i
                                            class="fa fa-eye"></i> <span>التفاصيل</span>
                                </a>
                            </div>
                            <div class="col-xs-7">
                                @if($product->status==1)
                                    <a class="btn btn-default btn-block btn-xs text-center" href="{{route('dashboard.product_user', $product->id)}}">
                                        <i class="fa fa-shopping-cart"></i> <span>سوق هذا المنتج</span>
                                    </a>
                                @else
                                    <a class="btn btn-default btn-block btn-xs text-center" disabled="" href="#">
                                        <i class="fa fa-shopping-cart"></i> <span>سوق هذا المنتج</span>
                                    </a>
                                @endif
                            </div>
                        </div>

                    </div>
                </div>
                @endif
            @endforeach
            @if($num==0)
                <h5 class="text-center">لا توجد حاليا أية أنت منتجات مشترك في تسويقها</h5>
            @endif
        </div>
    </div>

    <div class="panel panel-danger">
        <div class="panel-heading"><h5>فرصة تسويقية</h5></div>
        <div class="panel-body">
            @foreach($products as $product)
                @if(!$product->pivoted)
                    <div class="col-md-3 col-sm-4">
                        <div class="box">
                            <a class="img-wrapper" href="{{route('dashboard.product', $product->id)}}" style="background-image: url({{asset("public/uploads/images/".$product->image)}})">
                                <span class="price">{{$product->price}} ريال</span>
                                @if($user->percentage and $user->percentage!="")
                                    <span class="percentage">{{$user->percentage}}%</span>
                                @else
                                    <span class="percentage">{{$product->percentage}}%</span>
                                @endif
                            </a>
                            <h5>{{$product->name}}</h5>
                            <p class="desc">{{$product->short_description}}</p>
                            <div class="row">
                                <div class="col-xs-5">
                                    <a class="btn btn-info btn-block btn-xs text-center" href="{{route('dashboard.product', $product->id)}}"><i
                                                class="fa fa-eye"></i> <span>التفاصيل</span>
                                    </a>
                                </div>
                                <div class="col-xs-7">
                                    @if($product->status==1)
                                        <a class="btn btn-default btn-block btn-xs text-center" href="{{route('dashboard.product_user', $product->id)}}">
                                            <i class="fa fa-shopping-cart"></i> <span>سوق هذا المنتج</span>
                                        </a>
                                    @else
                                        <a class="btn btn-default btn-block btn-xs text-center" disabled="" href="#">
                                            <i class="fa fa-shopping-cart"></i> <span>سوق هذا المنتج</span>
                                        </a>
                                    @endif
                                </div>
                            </div>

                        </div>
                    </div>
                @endif
            @endforeach
        </div>
    </div>

</div>

<style>
    .panel-danger .panel-heading h5{
        color: #ffff;
        margin: 0px;
        font-weight: bold;
    }
    .products {
        margin-top: 10px;
    }

    .box {
        width: 100%;
        padding: 10px;
        border: 1px solid #b0b0b0;
        margin-bottom: 20px;
    }

    .box .img-wrapper {
        position: relative;
        width: 100%;
        display: block;
        min-height: 167px;
        background-size: cover;
        background-position: center center;
    }

    .box .img-wrapper .price {
        color: #fff;
        text-shadow: 1px 1px #333;
        position: absolute;
        bottom: -2px;
        right: 2px;
    }

    .box .img-wrapper .percentage {
        color: #fff;
        text-shadow: 1px 1px #333;
        position: absolute;
        bottom: -2px;
        left: 2px;
    }

    .box img {
        width: 100%;
    }

    .box h5 {
        text-align: center;
        font-weight: bold;
        overflow: hidden;
        line-height: 20px;
    }

    .box h6 {
        font-weight: bold;
    }

    .box .desc {
        text-align: justify;
        height: 124px;
        overflow: hidden;
    }

    .box .btn {
        border-radius: 0px;
    }
</style>

<style>
    .google, .facebook, .twitter, .linkedin {
        display: block;
        text-align: center;
        color: #fff;
    }

    .linkedin:hover, .linkedin:active, .google:hover, .facebook:hover, .twitter:hover, .google:active, .facebook:active, .twitter:active {
        color: #fff;
    }

    .linkedin .fa, .google .fa, .facebook .fa, .twitter .fa {
        display: block;
        text-align: center;
        font-size: 22px;
        margin-bottom: 10px;
        color: #fff;
    }

    .linkedin {
        background: darkblue;
    }

    .google {
        background: #e8332f;
    }

    .facebook {
        background: #0d71bb;
    }

    .twitter {
        background: #0d5a9c;
    }

    .remodal h3 {
        margin-bottom: 20px;
        margin-top: 0px;
    }

    .reloading {
        color: #bc1e2c;
        text-align: center;
        margin-top: 20px;
    }

    .data {
        display: block;
    }

    .data .url, .data .short_url {
        padding: 2px 0px;
        color: #027a98;
        background: #eee;
        border: 1px solid #c4c4c4;
    }
</style>

<script>

    $(document).on('closed', '.remodal', function () {
        surl = "";
        $(".data").fadeOut("fast");
        $(".reloading").fadeIn("fast");
        $(".data .url").html('');
        $(".data .short_url").html('');
    });

    $(document).on('opened', '.remodal', function () {
        var url = $(this).data("url");
        $.ajax({
            method: "GET",
            url: url,
            dataType: "json"
        }).done(function (data) {
            $(".reloading").fadeOut(100);
            setTimeout(function () {
                $(".data .url").html('<a href="' + data.url + '">' + data.url + '</a>');
                $(".data .short_url").html('<a href="' + data.short_url + '">' + data.short_url + '</a>');
                surl = data.short_url;
                $(".data").fadeIn("slow");
            }, 110);
        }).fail(function () {
            $(".data").fadeOut("fast");
            $(".reloading").fadeIn("fast");
            //alert("لقد وقع خطأ ما, الرجاء إعادة تحميل الصفحة و المحاولة من جديد");
        });
    });

    function google() {
        var link = "https://plus.google.com/share?url=" + surl;
        window.open(link, 'مشاركة على  غوغل +', 'width=400, height=300');
    }

    function facebook() {
        var link = "https://www.facebook.com/sharer/sharer.php?u=" + surl;
        window.open(link, 'مشاركة على  فايسبوك', 'width=400, height=300');
    }

    function twitter() {
        var link = "https://twitter.com/home?status=" + surl;
        window.open(link, 'مشاركة على  تويتر', 'width=400, height=300');
    }

    function linkedin() {
        var link = "https://www.linkedin.com/shareArticle?mini=true&url=" + surl + "&title=&summary=&source=";
        window.open(link, 'مشاركة على  تويتر', 'width=400, height=300');
    }

</script>

resources/views/front/dashboard/unconfirmed.blade.php
@extends("front.app")

@section("title", "حسابي الشخصي")
@section("menu", 5)

@section("content")

    <div class="container" style="margin-top: 50px; margin-top: 100px">
        <div class="alert alert-success text-center">حسابك مازال غير مفعل, يجب تفقد بريدك الإلكتروني للحصول على رابط التفعيل</div>
    </div>

@endsection